format_version = 2

[apps.UsdView]
identifier = 'foundation.wabi.UsdView'
product = 'UsdView'
version = '1.0.0'
category = 'public.app-category.graphics-design'
icon = 'usdview.png'

[apps.UsdView.plist]
commit = '$(COMMIT_HASH)'
CFBundleDocumentTypes = [ { type = "dict", value = { CFBundleTypeExtensions = [ 'usd', 'usda', 'usdc', 'usdz' ], CFBundleTypeIconFile = 'AppIcon.icns', CFBundleTypeName = 'Universal Scene Description File', CFBundleTypeRole = 'Editor', LSIsAppleDefaultForType = true, LSItemContentTypes = [ 'com.pixar.universal-scene-description', 'com.pixar.universal-scene-description-mobile', 'com.pixar.usd.ascii', 'com.pixar.usd.crate' ], CFBundleTypeIconSystemGenerated = true } } ]