name: Run Tests (Ubuntu x86/64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: ðŸ‘¨â€ðŸ’» Install CxxStdlib
        run: sudo apt install libstdc++-12-dev
      - name: ðŸ“™ Install BZ2
        run: sudo apt install libbz2-dev
      - name: ðŸ““ Install ZLib
        run: sudo apt install zlib1g-dev
      - name: ðŸ Install Python
        run: sudo apt install python3-dev
      - name: ðŸ–¼ Install FreeGLUT
        run: sudo apt install freeglut3-dev
      - name: ðŸš€ Install Boost
        run: sudo apt install libboost-all-dev
      - name: ðŸ–¥ï¸ Install X11
        run: sudo apt install libxcursor-dev libxt-dev libxi-dev libxinerama-dev libxrandr-dev
      - name: ðŸ§ª Test
        run: |
          echo "### Disabled Tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pre Swift 5.10 toolchains do not support Cxx Interop enabled testing targets on Linux." >> $GITHUB_STEP_SUMMARY
      - name: ðŸŽ¬ Run
        run: swift run
