name: Swift (Ubuntu x86/64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: ğŸ“™ Install BZ2
        run: sudo apt install libbz2-dev
      - name: ğŸ““ Install ZLib
        run: sudo apt install zlib1g-dev
      - name: ğŸ Install Python
        run: sudo apt install python3-dev
      - name: ğŸš€ Install Boost
        run: sudo apt install libboost-all-dev
      - name: ğŸ“¦ Build
        run: swift build -c release --target UsdView
