name: Swift (Ubuntu x86/64)

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: ğŸ‘¨â€ğŸ’» Install CxxStdlib
        run: sudo apt install libstdc++-12-dev
      - name: ğŸ—œï¸ Install DEFLATE
        run: sudo apt install libdeflate-dev
      - name: ğŸ“™ Install BZ2
        run: sudo apt install libbz2-dev
      - name: ğŸ““ Install ZLib
        run: sudo apt install zlib1g-dev
      - name: ğŸ Install Python
        run: sudo apt install python3-dev
      - name: ğŸ–¼ Install FreeGLUT
        run: sudo apt install freeglut3-dev
      - name: ğŸš€ Install Boost
        run: sudo apt install libboost-all-dev
      - name: ğŸ–¥ï¸ Install X11
        run: sudo apt install libxcursor-dev libxt-dev libxi-dev libxinerama-dev libxrandr-dev
      - name: ğŸ’» Install GTK
        run: sudo apt install libgtk-4-dev clang
      - name: ğŸ“¦ Build
        run: swift build -c release --target UsdView
